### ISSUE TITLE
Do not show loading state when changing pages after the first time

### ISSUE THREAD

**Issue by dextermb** [langleyfoxall/react-dynamic-data-table#48] opened 2018-12-12 15:18 UTC
After the initial load the loading state should not be displayed. For example, when switching between pages it should not swap back to the loading state each time, it should rather display the already loaded data until the new result set is swapped in.

**Comment by dextermb** [comment] 2018-12-12 15:19
Addition: This would be for the [AjaxDynamicDataTable](https://github.com/langleyfoxall/react-dynamic-data-table/blob/master/src/AjaxDynamicDataTable.jsx).

**Comment by DivineOmega** [comment] 2018-12-12 15:22
Duplicate of #35.

**Closed by DivineOmega** 2018-12-12 15:22 UTC
